# Generated by Django 5.1.3 on 2024-12-03 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmer',
            name='phone',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
